import { ElementMixin } from '@vaadin/component-base/src/element-mixin.js';
import { ThemeDetectionMixin } from '@vaadin/vaadin-themable-mixin/vaadin-theme-detection-mixin.js';

import { AnchorNavElement } from './vcf-anchor-nav.js';

/**
 * Fired when the section element itself receives focus, as opposed to one of
 * the elements inside it.
 */
export type AnchorNavSectionFocusEvent = CustomEvent<null>;

export interface AnchorNavSectionCustomEventMap {
  'section-focus': AnchorNavSectionFocusEvent;
}

export interface AnchorNavSectionEventMap extends HTMLElementEventMap, AnchorNavSectionCustomEventMap {}

/**
 * `<vcf-anchor-nav-section>`
 * Section element used inside `vcf-anchor-nav`.
 *
 * ```html
 * <vcf-anchor-nav-section name="Section 1"></vcf-anchor-nav-section>
 * ```
 *
 * ### Styling
 *
 * The following custom properties are available for styling:
 *
 * Custom property | Description | Default
 * ----------------|-------------|-------------
 * `--anchor-nav-section-border-width` | `border-width` of section. | `0`
 * `--anchor-nav-section-border-color` | `border-color` of section. | `#666`
 * `--anchor-nav-section-header-padding` | `padding` of the "header" part. | `1rem`
 * `--anchor-nav-section-content-padding` | `padding` of the "content" part. | `1rem`
 *
 * The following shadow DOM parts are available for styling:
 *
 * Part name | Description
 * ----------------|----------------
 * `header` | Header section.
 * `content` | Content section.
 *
 * @fires {CustomEvent} section-focus - Fired when the section element itself receives focus.
 * @mixes ElementMixin
 * @mixes ThemeDetectionMixin
 */
declare class AnchorNavSectionElement extends ThemeDetectionMixin(ElementMixin(HTMLElement)) {
  /**
   * The tag name of this element.
   */
  static readonly is: string;

  /**
   * Whether the element is a `<vcf-anchor-nav-section>`.
   */
  static isSame(el: Element): boolean;

  /**
   * Used to set corresponding tab label and default header text.
   * If not set defaults to "Section <index>".
   */
  name: string;

  /**
   * Id of corresponding tab element.
   *
   * @attr {string} tab-id
   */
  tabId: string;

  /**
   * The `<vcf-anchor-nav>` this section belongs to, or `null` when the section
   * is not a child of one.
   */
  readonly nav: AnchorNavElement | null;

  /**
   * All sections of the containing nav, or `null` when there is no nav.
   */
  readonly navSections: AnchorNavSectionElement[] | null;

  /**
   * The tab that navigates to this section: the one slotted into the section
   * when there is one, the tab generated by the nav otherwise.
   */
  readonly tab: HTMLElement | null | undefined;

  /**
   * The tab slotted into this section, if any.
   */
  readonly slottedTab: HTMLElement | null | undefined;

  /**
   * The tab generated for this section inside the nav's `vaadin-tabs`, if any.
   */
  readonly navTab: HTMLElement | null | undefined;

  /**
   * The current location with the hash set to this section's id.
   */
  readonly url: URL;

  /**
   * Id used for the generated tab when `tabId` is not set.
   */
  readonly defaultTabId: string;

  /**
   * Position of this section among the sections of the containing nav, or
   * `null` when there is no nav.
   */
  readonly sectionIndex: number | null;

  /**
   * Name used when `name` is not set.
   */
  readonly defaultName: string;

  /**
   * Id used when the element has no id.
   */
  readonly defaultId: string;

  /**
   * Id of the header element this section is labelled by.
   */
  readonly headerId: string;

  addEventListener<K extends keyof AnchorNavSectionEventMap>(
    type: K,
    listener: (this: AnchorNavSectionElement, ev: AnchorNavSectionEventMap[K]) => void,
    options?: AddEventListenerOptions | boolean
  ): void;

  removeEventListener<K extends keyof AnchorNavSectionEventMap>(
    type: K,
    listener: (this: AnchorNavSectionElement, ev: AnchorNavSectionEventMap[K]) => void,
    options?: EventListenerOptions | boolean
  ): void;
}

declare global {
  interface HTMLElementTagNameMap {
    'vcf-anchor-nav-section': AnchorNavSectionElement;
  }
}

export { AnchorNavSectionElement };
